### PR TITLE
Allow to use stable version of tactician and tests php 7.0

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
I'm not familiar with Spec but something goes wrong on php 7.0 @norzechowicz

**Comment by norberttech** [comment]
@snapshotpl could you try to update phpsec?

**Comment by snapshotpl** [comment]
@norzechowicz I have just run composer install and then tests fail. I have php 7.0 workspace

**Comment by norberttech** [comment]
Yea but could you try to update phpspec version, maybe ^2.1 for example?

**Comment by snapshotpl** [comment]
I have installed:

```
  - Installing phpspec/phpspec (2.1.1)
    Downloading: 100%
```

**Comment by snapshotpl** [comment]
Same like here https://travis-ci.org/isolate-org/tactician-bridge/jobs/138094047

**Comment by norberttech** [comment]
Please open composer.json file, and change phpspec dependency version from `2.1.*` into `^2.1`, then run composer update and check how it works.

**Comment by snapshotpl** [comment]
Works ;) Which version of phpspec starts this break?

**Comment by norberttech** [comment]
I dont rememer when phpspec starts supporting php 7.0 however please update this PR with phpspec `^2.1` dependency version

**Comment by snapshotpl** [comment]
@norzechowicz great! Can you release this changes?

**Comment by norberttech** [comment]
done, could you create similar PR's for other isolate repositories?

**Comment by snapshotpl** [comment]
A lot of work for me now. In this moment I create zend module for isolate. If I found some issues like here, or I will finish, then I will try, but I don't promiss anything

**Pull request merged**
